Gui:
  rows: 5
  title: 'Ставки до 1м, необходимо 5 ставок до начала'
  
  glasses:
    data: 15
    slots:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 17
      - 27
      - 36
      - 37
      - 38
      - 39
      - 40
      - 41
      - 42
      - 43
      - 44
      - 35
  player:
    name: '{prefix} &6{name} {suffix}'
    lore:
      - ''
      - '&6● &fСтавка: &6{bet}'
      - '&6● &fШанс на победу: &6~{percent}%'
      - ''
  barrier:
    slot: 15
    name: '&cСтавок пока что нет :('
    lore:
      - 'Ставок 0'
  info:
    slot: 40
    name: '&6-- ИНФОРМАЦИЯ --'
    lore:
      - ''
      - ''
      - '&6● &fБанк: &6{total_money}$'
      - '&6● &fДо розыгрыша: &6{time}'
      - ''
      - '&fЧтобы поставить ставку,'
      - '&fпропишите: &6/bet (ставка)'
   
    
  
Settings:
  no_time: 'Отсчёт не начался'
  time: 180
  players_to_start_timer: 5
  max_bet: 1000000
  location: 'world, 0, 0, 0'
Messages:
  prefix: '&6Казино &7>> &f'
  
  using: '&fИспользование команды: /bet [ставка]'
  success: '&aСтавка успешно поставлена'
  win: '&fИгрок &e{player} &fвыиграл &6{money}$ &fу крупье &7(Шанс - ~{percent}%)'
  croupier: '&cПодойдите к крупье поближе'
  
  sets: '&aВы успешно поставили локацию крупье'
  bet:
    already: '&cУ вас уже стоит ставка!'
    double_error: '&cУказанная сумма не является числом'
    
    minimum: 1000
    moneys: '&cМинимальная ставка 1000!'
    big_bet: '&cСумма ставки выше допустимой'
    no_eco: '&cУ вас нету такой суммы'

    
    
    

    
    
   ### 
###

Gui-two:
  rows: 5
  title: 'Ставки до 1м, необходимо 5 ставок до начала'
  
  glasses:
    data: 15
    slots:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 17
      - 27
      - 36
      - 37
      - 38
      - 39
      - 40
      - 41
      - 42
      - 43
      - 44
      - 35
  player:
    name: '{prefix} &6{name} {suffix}'
    lore:
      - ''
      - '&6● &fСтавка: &6{bet}'
      - '&6● &fШанс на победу: &6~{percent}%'
      - ''
  barrier:
    slot: 15
    name: '&cСтавок пока что нет :('
    lore:
      - 'Ставок 0'
  info:
    slot: 40
    name: '&6-- ИНФОРМАЦИЯ --'
    lore:
      - ''
      - ''
      - '&6● &fБанк: &6{total_money}$'
      - '&6● &fДо розыгрыша: &6{time}'
      - ''
      - '&fЧтобы поставить ставку,'
      - '&fпропишите: &6/bet (ставка)'
   
    
  
Settings-two:
  no_time: 'Отсчёт не начался'
  time: 180
  players_to_start_timer: 5
  max_bet: 1000000
  location: 'world, 0, 0, 0'
Messages-two:
  prefix: '&6Казино &7>> &f'
  
  using: '&fИспользование команды: /bet [ставка]'
  success: '&aСтавка успешно поставлена'
  win: '&fИгрок &e{player} &fвыиграл &6{money}$ &fу крупье &7(Шанс - ~{percent}%)'
  croupier: '&cПодойдите к крупье поближе'
  
  sets: '&aВы успешно поставили локацию крупье'
  bet:
    already: '&cУ вас уже стоит ставка!'
    double_error: '&cУказанная сумма не является числом'
    
    minimum: 1000
    moneys: '&cМинимальная ставка 1000!'
    big_bet: '&cСумма ставки выше допустимой'
    no_eco: '&cУ вас нету такой суммы'
  